
spring:
  application:
    name: universitymanagement



  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5433/uml
  jpa:
    hibernate:
      ddl-auto: update


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/University-Management


  logging:
    level:
      org.springframework.security: TRACE

  jwt:
    auth:
      converter:
        resource-id: demo
        principle-attribute: preferred_username


server:
  port: 8072

keycloak:
  server-url: http://localhost:8088
  realm: University-Management
  client-id: identity-service
  client-secret: b1JQCK70CfqdWguqj0dDn3nvN22QaLvI

#
#minio:
#  endpoint: http://localhost:9000
#  access-key: minioadmin
#  secret-key: minioadmin
#  bucket: my-application-bucket