
spring:
  application:
    name: universitymanagement



  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://15.235.209.49:1688/postgres
    username: ratanak
    password: YOUR_DATABASE_PASSWORD


  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  https://auth.careerpatch.site/realms/university

logging:
  level:
    org.springframework.security: TRACE

keycloak:
  server-url:  https://auth.careerpatch.site
  realm: university
  client-id: identity-service
  client-secret: b1JQCK70CfqdWguqj0dDn3nvN22QaLvI


#minio:
#  endpoint: http://localhost:9000
#  access-key: minioadmin
#  secret-key: minioadmin
server:
  port: 8072
#  bucket: my-application-bucket